name = "adascore/aiken"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'adascore/aiken'"

[repository]
user = "adascore"
project = "aiken"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.3.0"
source = "github"
